/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.c
 #	source generated by 4D Plugin Wizard
 #	Project : System
 #	author : jf
 #	17/03/2013
 #
 # --------------------------------------------------------------------------------*/


#include "4DPluginAPI.h"
#include "4DPlugin.h"

#if VERSIONWIN
#include <Windows.h>
#endif

void PluginMain( long selector, PA_PluginParameters params )
{
	switch( selector )
	{
// --- systeme

		case 1 :
			systeme_infos( params );
			break;

	}
}

// ------------------------------------ systeme -----------------------------------


void systeme_infos( PA_PluginParameters params )
{
	PA_Unichar* returnValue_uchars;

	// --- write the code of systeme_infos here...

	PA_ReturnString( params, returnValue_uchars );
}

